name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test_pyenv:
    runs-on: ubuntu-latest
    name: install pyenv
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup pyenv
        uses: "gabrielfalcao/pyenv-action@v18"
        with:
          default: 3.12.7
          versions: 3.11.10

      - name: Test with pytest
        run: |
          python3 -m pip install pytest
          python3 -m pytest -v
